AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Grithub Backend FastAPI Application

Resources:
  GrithubFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: app.app
      Runtime: python3.9
      MemorySize: 256
      Timeout: 30
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
